# Generated by Django 2.1.5 on 2019-12-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBusSeat', '0002_auto_20191213_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_bookings',
            name='status',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
